[package]
name = "pong"
version = "0.1.0"
authors = ["Glen Sargent <glensarg@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.amethyst]
amethyst = "0.15.3"
features = ["vulkan"]
